# Generated by Django 3.2.21 on 2023-09-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
    ]
