name: omise
description: Omise SDK for flutter
version: 0.0.1

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: #latest

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
